# Generated by Django 6.0.3 on 2026-03-17 12:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('WA', 'WhatsApp'), ('TG', 'Telegram'), ('FB', 'Facebook')], help_text='Application platform', max_length=2)),
                ('bot_name', models.CharField(help_text='Name of the bot', max_length=32)),
                ('desc', models.CharField(help_text='Description of the bot', max_length=100)),
                ('bot_number', models.CharField(help_text='Bot phone number', max_length=12)),
                ('config_json', models.JSONField(default=dict, help_text='Bot specific configuration')),
                ('is_active', models.BooleanField(default=True, help_text='Active status of the bot')),
                ('language', models.CharField(choices=[('hi', 'Hindi'), ('en', 'English')], default='hi', help_text='Language code', max_length=5)),
                ('init_state', models.CharField(help_text='Initial state identifier', max_length=50)),
                ('creation_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Flow Name', max_length=20)),
                ('desc', models.CharField(help_text='Description of flow', max_length=100)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('smj_json', models.JSONField(help_text='JSON containing state machine definition')),
            ],
        ),
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_interaction_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user_misc', models.JSONField(default=dict, help_text='Miscellaneous user data')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_interface_users', to='bot_interface.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_interface_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bot Users',
                'unique_together': {('user', 'bot')},
            },
        ),
        migrations.AddField(
            model_name='bot',
            name='smj',
            field=models.ForeignKey(help_text='Flow to start with', on_delete=django.db.models.deletion.CASCADE, to='bot_interface.smj'),
        ),
        migrations.CreateModel(
            name='UserArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('WA', 'WhatsApp'), ('TG', 'Telegram'), ('FB', 'Facebook')], max_length=2)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_data', models.JSONField(help_text='Archived session data')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_interface_archives', to='bot_interface.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_interface_archives', to='bot_interface.botusers')),
            ],
        ),
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('WA', 'WhatsApp'), ('TG', 'Telegram'), ('FB', 'Facebook')], help_text='Application platform', max_length=2)),
                ('key1', models.CharField(blank=True, max_length=50, null=True)),
                ('value1', models.TextField(blank=True, null=True)),
                ('key2', models.CharField(blank=True, max_length=50, null=True)),
                ('value2', models.TextField(blank=True, null=True)),
                ('key3', models.CharField(blank=True, max_length=50, null=True)),
                ('value3', models.TextField(blank=True, null=True)),
                ('key4', models.CharField(blank=True, max_length=50, null=True)),
                ('value4', models.TextField(blank=True, null=True)),
                ('misc', models.JSONField(default=dict, help_text='Additional log data beyond 4 parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_interface_logs', to='bot_interface.bot')),
                ('smj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_interface.smj')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_interface_logs', to='bot_interface.botusers')),
            ],
            options={
                'verbose_name_plural': 'User Logs',
            },
        ),
        migrations.CreateModel(
            name='UserSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('WA', 'WhatsApp'), ('TG', 'Telegram'), ('FB', 'Facebook')], max_length=2)),
                ('phone', models.CharField(help_text="User's mobile number", max_length=15)),
                ('user_config', models.JSONField(default=dict, help_text='User specific configuration')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('current_session', models.JSONField(default=dict)),
                ('current_state', models.CharField(help_text="User's current state in the flow", max_length=50)),
                ('expected_response_type', models.CharField(choices=[('text', 'Text'), ('button', 'Button'), ('media', 'Media'), ('location', 'Location'), ('contact', 'Contact')], default='text', max_length=20)),
                ('misc_data', models.JSONField(default=dict, help_text='Miscellaneous session data')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_interface_sessions', to='bot_interface.bot')),
                ('current_smj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_interface.smj')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_interface_sessions', to='bot_interface.botusers')),
            ],
            options={
                'verbose_name_plural': 'User Sessions',
            },
        ),
    ]
